$transparent    = rgba(00000000)
$background     = rgb(181F21)
$foreground     = rgb(D8E2E6)
$cursor         = rgb(D8E2E6)
$green          = rgb(A7DFB6)
$blue           = rgb(9CD1E8)
$black          = rgb(101517)
$red            = rgb(F498A5)
$yellow         = rgb(F2E1A6)
