# eww
exec-once = eww open bar_0

# other hyprland apps
exec-once = hypridle
exec-once = hyprsunset

# plugins
exec-once = hyprpm reload -n

# polkit agent
exec-once = systemctl --user start hyprpolkitagent

# ssh-agent
exec-once = ssh-agent -D -a $SSH_AUTH_SOCK
exec-once = ~/.local/bin/load_ssh_keys.sh 

# udiskie
exec-once = udiskie
